[build]
  command = "./build.sh"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/Skillvendor/go-rarity"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
