[build]
  command = "./build.sh"
  publish = "public"

[functions]
  directory = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/Skillvendor/api-ngmi"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-ngmi/:splat"
  status = 200
