CREATE TABLE nt_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  citizen_wallet text NOT NULL UNIQUE,
  access_wallet text NOT NULL UNIQUE,
  transaction_link text NOT NULL UNIQUE,

  transaction_verified BOOLEAN DEFAULT FALSE,
  transaction_valid BOOLEAN DEFAULT FALSE,

  discord_handle text NOT NULL UNIQUE,
  twitter_handle text NOT NULL UNIQUE,

  valid BOOLEAN DEFAULT FALSE
);

CREATE UNIQUE INDEX idx_nt_payments_citizen_wallets
ON nt_payments(citizen_wallet);

CREATE UNIQUE INDEX idx_nt_payments_access_wallet_valid
ON nt_payments(access_wallet, valid);

CREATE INDEX idx_nt_payments_transaction_verified
ON nt_payments(transaction_verified);

CREATE INDEX idx_nt_payments_valid
ON nt_payments(valid);

create extension if not exists moddatetime schema extensions;

create trigger
  handle_updated_at before update
on nt_payments
for each row execute
  procedure moddatetime(updated_at);
