CREATE TABLE reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  description text,
  logo text,
  assets text[],
  chain text,
  rating decimal,
  rating_breakdown jsonb,
  tags text[],
  scores jsonb,
  socials jsonb,
  report_details jsonb,
  detailed_analysis jsonb,
  report_details_link text,
  detailed_analysis_link text,
  published boolean DEFAULT FALSE
);

create extension if not exists moddatetime schema extensions;

-- assuming the table name is "todos", and a timestamp column "updated_at"
-- this trigger will set the "updated_at" column to the current timestamp for every update
create trigger
  handle_updated_at before update
on reports
for each row execute
  procedure moddatetime(updated_at);