CREATE TABLE ntpayments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  citizen_wallet text NOT NULL UNIQUE,
  access_wallet text NOT NULL UNIQUE,
  transaction_link text NOT NULL UNIQUE,

  transaction_verified BOOLEAN,
  transaction_valid BOOLEAN,

  discord_handle text NOT NULL UNIQUE,
  twitter_handle text NOT NULL UNIQUE
);

CREATE UNIQUE INDEX idx_ntpayments_citizen_wallets
ON ntpayments(citizen_wallet);

CREATE UNIQUE INDEX idx_ntpayments_access_wallet
ON ntpayments(access_wallet);

CREATE INDEX idx_ntpayments_transaction_verified
ON ntpayments(transaction_verified);

create extension if not exists moddatetime schema extensions;

create trigger
  handle_updated_at before update
on ntpayments
for each row execute
  procedure moddatetime(updated_at);
