CREATE TABLE collections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  socials jsonb,
  mint_info jsonb,
  mint_time timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  logos jsonb,
  research jsonb,
  report_type int,
  tier int,
  published boolean DEFAULT FALSE,
  name text,
  description text
);
