CREATE TABLE admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  auth_token text,
  access_level int DEFAULT 1
);

CREATE UNIQUE INDEX idx_admins_username
ON admins(username);

CREATE INDEX idx_admins_token
ON admins(auth_token);

create extension if not exists moddatetime schema extensions;

create trigger
  handle_updated_at before update
on admins
for each row execute
  procedure moddatetime(updated_at);
