CREATE TABLE reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  description text,
  logo text,
  chain text,
  rating decimal,
  rating_breakdown jsonb,
  tags text[],
  socials jsonb,
  report_details jsonb,
  detailed_analysis jsonb,
  report_details_link text,
  detailed_analysis_link text,
  published boolean DEFAULT FALSE
);