CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  address text NOT NULL UNIQUE,
  nonce bigint NOT NULL,
  auth_token text,
  access_level int DEFAULT 1
);

CREATE UNIQUE INDEX idx_users_address
ON users(address);

CREATE INDEX idx_users_auth_token
ON users(auth_token);
