CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  address text NOT NULL UNIQUE,
  nonce text NOT NULL,
  auth_token text,
  access_level int DEFAULT 1
);

CREATE UNIQUE INDEX idx_users_address
ON users(address);

CREATE INDEX idx_users_auth_token
ON users(auth_token);

create extension if not exists moddatetime schema extensions;

-- assuming the table name is "todos", and a timestamp column "updated_at"
-- this trigger will set the "updated_at" column to the current timestamp for every update
create trigger
  handle_updated_at before update
on users
for each row execute
  procedure moddatetime(updated_at);
