CREATE TABLE transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  address text NOT NULL,
  transaction_id text NOT NULL UNIQUE,
  state int NOT NULL
);

-- CREATE UNIQUE INDEX idx_transaction_address
-- ON transactions(address);

CREATE INDEX idx_transactions_address_state
ON transactions(address, state);

create extension if not exists moddatetime schema extensions;

create trigger
  handle_updated_at before update
on transactions
for each row execute
  procedure moddatetime(updated_at);